article/urls.py
from django.urls import path
from . import views
# 引入path
app_name = 'article'

urlpatterns = [
    # 首页
    path('article/',views.article, name='article'),
    # 文章列表
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>', views.artilce_detail, name='article_detail'),
    # 创建文章
    path('article-create/<int:mark_fu>', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>', views.article_delete, name='article_delete'),
    # 修改文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    # 富文本修改文章
    path('article-update1/<int:id>/', views.article_update1, name='article_update1'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    # 书籍列表
    path('book-list/', views.book_list, name='book_list'),
    # 书籍详情
    path('book-detail/<int:id>/', views.book_detail, name='book_detail'),
    # 书籍下载
    path('book-download/<int:id>/', views.download, name='download'),
]

comment/urls.py
from django.urls import path
from . import views
app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_conmment'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 用户管理页面
    path('admin/', admin.site.urls),
    # 文章界面
    path('article/', include('article.urls', namespace='arctile')),
    # 用户管理界面
    path('profile/', include('userprofile.urls', namespace='userporfile')),
    # 密码重置
    path('password-reset/', include('password_reset.urls')),
    # 用户评论
    path('comment/', include("comment.urls", namespace='comment')),
    # 上传文件
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # 书籍
    path('book/', include('book.urls', namespace='book')),
    # 视频
    path('video/', include('video.urls', namespace='video')),
    # 图片
    path('photo/', include('photo.urls', namespace='photo')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/artilce/create.html
{% extends 'base1.html' %}
{% load staticfiles %}
{% block title %}
    富文本编辑
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div id="article_update">
            <!-- 提交文章的表单 -->
            <form method="post" action="/article/article-create/2" enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div id="update_before">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div id="update_after">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <div>
                        {{ article_post_form.media }}
                        {{ article_post_form.body1}}
                    </div>

                </div>
                <div id="update_column">
                    <label for="column">标签:</label>
                    <select id="column" name="column" >
                        <option value="none">请选择标签...</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div id="create_img">
                    <label for="avatar">标题图(下图为默认图片)</label>
                    <div id="show-pic">
                        <img id="book-pic" src="{% static 'images/moarticle.jpg' %}" alt="">
                    </div>
                    <input type="file" onchange="show(this)"  name="avatar" id="avatar">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" onclick="return create_over()">完成</button>
            </form>
</div>
{% endblock content %}
{% block js %}
<script>
    function show(f) {
        //得到上传文件的值
        var fileName=document.getElementById("avatar").value;
            //返回String对象中子字符串最后出现的位置.
        var seat=fileName.lastIndexOf(".");
            //返回位于String对象中指定位置的子字符串并转换为小写.
        var extension=fileName.substring(seat).toLowerCase();
            //判断允许上传的文件格式
        if(extension!=".jpg"&&extension!=".jpeg"&&extension!=".gif"&&extension!=".png"&&extension!=".bmp"){
            alert("不支持"+extension+"文件的上传!");
            document.getElementById("book-pic").src = "{% static 'images/moarticle.jpg' %}";
            return false;
        }else{
            var rd = new FileReader();//创建文件读取对象
            if(f.files.length >= 1){
                var files = f.files[0];//获取file组件中的文件
                rd.readAsDataURL(files);//文件读取装换为base64类型
                rd.onloadend = function (e) {
                //加载完毕之后获取结果赋值给img
                    document.getElementById("book-pic").src = this.result;
                }
                }else{
                    document.getElementById("book-pic").src = "{% static 'images/moarticle.jpg' %}";
                }
            }
    }
    <!--提交前判断-->
    function create_over(){
        var r = confirm('确定创建行文章吗？');
        if(r==true){
            var title_name = $('#title').val();
            if (title_name){
                return true;
            }else {
                alert('请传入文章标题!');
                return false;
            }
        }else{
            return false;
        }
    }
</script>
{% endblock %}

templates/artilce/create1.html
{% extends 'base1.html' %}
{% load staticfiles %}
{% block title %} Markdown {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
{% block head %}
    <style>
        .content{
            padding: 0 20px;
            background-color: #fff;
            border: 1px solid #EAEAEA;
            border-radius: 4px;
            min-height: 600px;
        }
    </style>
{% endblock %}
<div id="article_update">
            <!-- 提交文章的表单 -->
            <form method="post" action="/article/article-create/1" enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div id="update_before">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div id="update_after">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <div id="update_column">
                    <label for="column">类型:</label>
                    <select id="column" name="column" >
                        <option value="none">请选择类型...</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div id="create_img">
                    <label for="avatar">标题图(下图为默认图片)</label>
                    <div id="show-pic">
                        <img id="book-pic" src="{% static 'images/moarticle.jpg' %}" alt="">
                    </div>
                    <input type="file" onchange="show(this)"  name="avatar" id="avatar">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" onclick="return create_over()">完成</button>
            </form>
</div>
{% endblock content %}
{% block js %}
<script>
    function show(f) {
        //得到上传文件的值
        var fileName=document.getElementById("avatar").value;
            //返回String对象中子字符串最后出现的位置.
        var seat=fileName.lastIndexOf(".");
            //返回位于String对象中指定位置的子字符串并转换为小写.
        var extension=fileName.substring(seat).toLowerCase();
            //判断允许上传的文件格式
        if(extension!=".jpg"&&extension!=".jpeg"&&extension!=".gif"&&extension!=".png"&&extension!=".bmp"){
            alert("不支持"+extension+"文件的上传!");
            document.getElementById("book-pic").src = "{% static 'images/moarticle.jpg' %}";
            return false;
        }else{
            var rd = new FileReader();//创建文件读取对象
            if(f.files.length >= 1){
                var files = f.files[0];//获取file组件中的文件
                rd.readAsDataURL(files);//文件读取装换为base64类型
                rd.onloadend = function (e) {
                //加载完毕之后获取结果赋值给img
                    document.getElementById("book-pic").src = this.result;
                }
                }else{
                    document.getElementById("book-pic").src = "{% static 'images/moarticle.jpg' %}";
                }
            }
    }
    <!--提交前判断-->
    function create_over(){
        var r = confirm('确定创建行文章吗？');
        if(r==true){
            var title_name = $('#title').val();
            if (title_name){
                var title_body = $('#body').val();
                if(title_body){
                    return true;
                }else{
                    alert('请传入文章内容!');
                    return false;
                }
            }else {
                alert('请传入文章标题!');
                return false;
            }
        }else{
            return false;
        }
    }
</script>
{% endblock %}

templates/artilce/detail.html
{% extends "base1.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}
{% block head %}
    <style>
        .content {
            padding: 0 20px;
            background-color: #fff;
            border: 1px solid #EAEAEA;
            border-radius: 4px;
        }
    </style>
      <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'prism/prism.css' %}">
{% endblock %}
{% block content %}
<ol class="breadcrumb" style="background-color: white">
    <li class="breadcrumb-item"><a href="{% url 'arctile:article_list' %}">文章列表</a></li>
    <li class="breadcrumb-item"><a href="#">{{article.column}}</a></li>
    <li class="breadcrumb-item active">{{article.title}}</li>
</ol>
      <header class="article-header">
        <h1 class="article-title">
            <a href="">{{article.title}}</a>
        </h1>
        <div class="article-meta">
            <span class="item article-meta-time">
          <time class="time" data-toggle="tooltip" data-placement="bottom" title="{{article.created_time}}">
              <i class="glyphicon glyphicon-time"></i> {{article.created_time}}
          </time>
          </span>
            <span class="item article-meta-source" data-toggle="tooltip" data-placement="bottom" title="{{article.author}}"><i class="glyphicon glyphicon-globe"></i> {{article.author}}</span>
            <span class="item article-meta-category" data-toggle="tooltip" data-placement="bottom" title="{{article.column}}"><i class="glyphicon glyphicon-list"></i> <a href="program" title="">{{article.column}}</a></span>
            <span class="item article-meta-views" data-toggle="tooltip" data-placement="bottom" title="查看：{{ article.total_views}}"><i class="glyphicon glyphicon-eye-open"></i> 共{{article.total_views}}人围观</span>
            <span class="item article-meta-comment" data-toggle="tooltip" data-placement="bottom" title="评论：0"><i class="glyphicon glyphicon-comment"></i> 0评论</span> </div>
      </header>
      <article class="article-content">
        {% if article.body %}
            <p>{{ article.body|safe}}</p>
        {% else %}
            <p>{{ article.body1|safe}}</p>
        {% endif %}
        <p class="article-copyright hidden-xs">未经允许不得转载：<a href="">噼里啪啦博客</a> » <a href="article.html">php如何判断一个日期的格式是否正确</a></p>
      </article>
        <div class="article-tags">
            {% if user == article.author %}
                <a href="#" onclick="confirm_delete()">删除文章</a>
                {% if article.body %}
                    <a href="{% url 'article:article_update' article.id %}">修改文章</a>
                {% else %}
                    <a href="{% url 'article:article_update1' article.id %}">修改文章</a>
                {% endif %}
            {% endif %}
        </div>
      <div class="article-tags">标签：<a href="" rel="tag">空白</a></div>
      <div class="relates">
        <div class="title">
          <h3>相关推荐</h3>
        </div>
        <ul>
          <li><a href="article.html">php如何判断一个日期的格式是否正确</a></li>
        </ul>
      </div>
      <div class="title" id="comment">
        <h3>评论</h3>
      </div>
      <div id="respond" class="hidden-xs">
      {% if user.is_authenticated %}
        <form action="{% url 'comment:post_conmment' article.id %}" method="post" id="comment-form">
            {% csrf_token %}
          <div class="comment">
            <div class="comment-box">
              <textarea placeholder="请输入您的评论！" type="text" name="body" id="comment-textarea" cols="100%" rows="3" tabindex="1" ></textarea>
              <div class="comment-ctrl">
                <button type="submit"  id="comment-submit" tabindex="5">评论</button>
              </div>
            </div>
          </div>
        </form>
      {% else %}
          <div class="comment-signarea">
            <h3 class="text-muted">评论前必须登录！</h3>
            <p> <a href="#" class="btn btn-primary login" rel="nofollow" onclick="user_login()">立即登录</a> &nbsp; <a href="javascript:;" class="btn btn-default register" rel="nofollow">注册</a> </p>
          </div>
      {% endif %}
      </div>
      <div id="postcomments">
        <ol class="commentlist">
        {% for comment in comments %}
          <li class="comment-content"><span class="comment-f">#1</span>
            <div class="comment-avatar"><img class="avatar" src="" alt="" /></div>
            <div class="comment-main">
              <p>
                  <span class="address">{{comment.user}}</span><span class="time">{{ comment.created|date:"Y-m-d H:i:s" }}</span><br />
                  {{ comment.body|safe}}
              </p>
            </div>
          </li>
        {% endfor %}
        </ol>
      </div>
{% endblock content %}

templates/artilce/detail1.html
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}
<!--引入代码高亮插件-->
{% block head %}
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'prism/prism.css' %}">
{% endblock head %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 文章详情 -->
    <div id="detail_row">
        <ol class="breadcrumb" id="mianbao">
        <li class="breadcrumb-item"><a href="{% url 'arctile:article_list' %}">文章列表</a></li>
        <li class="breadcrumb-item"><a href="#">{{article.column}}</a></li>
        <li class="breadcrumb-item active">{{article.title}}</li>
        </ol>
        <!-- 标题及作者 -->
        <h3>{{ article.title }}</h3>
        <div class="xinxi">
            <span>作者：{{ article.author }}</span>
            <span>|</span>
            <span>阅读量:{{article.total_views}}</span>
            <span>|</span>
            <span>{{article.created_time}}</span>
            {% if user == article.author %}
                <a href="#" onclick="confirm_delete()">删除文章</a>
                {% if article.body %}
                    <a href="{% url 'article:article_update' article.id %}">修改文章</a>
                {% else %}
                    <a href="{% url 'article:article_update1' article.id %}">修改文章</a>
                {% endif %}

            {% endif %}
        </div>
        <!-- 文章正文 -->
        {% if article.body %}
            <div id="detail_zhengwen">​
                    <!-- 新增的目录 -->
                    {% if toc %}
                    <div id="detail_mulu">
                        <h5>
                            <a data-toggle="collapse" href="#collapseTwo">点击展开目录:</a>
                        </h5>
                        <div id="collapseTwo" class="panel-collapse collapse">
                            {{ toc|safe }}
                        </div>
                    </div>
                    {% endif %}
                <div id="detail_body">
                    <p>{{ article.body|safe}}</p>
                </div>
            </div>
        {% else %}
            <div id="detail_zhengwen">​
                <!-- 新增的目录 -->
                <div id="detail_body">
                    <p>{{ article.body1|safe}}</p>
                </div>
            </div>
        {% endif %}
        <div id="detail_time">
            栏目: <a href="">{{article.column}}</a>
            <span>最后更新:{{article.updated_time}}</span>
        </div>
        <!--发表评论区-->
        <div id="detail_comment">
            {% if user.is_authenticated %}
                <div id="post-comment">
                    <form action="{% url 'comment:post_conmment' article.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="body"><strong>我也要发言：</strong></label>
                            <textarea type="text" class="form-control" id="body" name="body"></textarea>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit">发送</button>
                    </form>
                </div>
            {% else %}
                <h5 class="row justify-content-center" id="pinlun_tishi">
                    请<a href="#" onclick="user_login()">登录</a>后发表评论
                </h5>
            {% endif %}
        </div>
        <!--评论显示区-->
        <div id="comment_area">
            <h5>共有{{ comments.count }}条评论</h5>
            <div>
                {% for comment in comments %}
            <p>
                <strong style="color: darkblue">
                    {{ comment.user }}
                </strong> 于
                <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 时说：
            </p>
            <pre style="font-family: inherit; font-size: 1em;">{{ comment.body }}</pre>
                 {% endfor %}
            </div>
        </div>
    </div>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }
</script>
{% endblock content %}

templates/artilce/list.html
{% extends "base1.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章列表
{% endblock title %}
{% block content %}
    <div class="title">
        <h3>后端程序</h3>
      </div>
      {% for article in articles %}
      <article class="excerpt excerpt-1">
          <a class="focus" href="{% url 'article:article_detail' article.id %}" title="">
              {% if article.avatar %}
                <img class="thumb"  src="{{ article.avatar.url }}" alt="">
              {% else %}
                <img class="thumb"  src="{% static 'images/moarticle.jpg' %}" alt="">
              {% endif %}
          </a>
        <header><a class="cat" href="">{{article.column}}<i></i></a>
          <h2><a href="{% url 'article:article_detail' article.id %}" title="{{article.title }}">{{article.title}}</a></h2>
        </header>
        <p class="meta">
          <time class="time"><i class="glyphicon glyphicon-time"></i> {{article.created_time}}</time>
          <span class="views"><i class="glyphicon glyphicon-eye-open"></i> 共{{article.total_views}}人围观</span>
            <a class="comment" href="article.html#comment"><i class="glyphicon glyphicon-comment"></i> 0个评论</a></p>
        {% if article.body %}
            <p class="note">{{article.body|safe|slice:"130"}}... </p>
        {% else %}
            <p class="note">{{article.body1|striptags|safe|slice:"130"}}... </p>
        {% endif %}
      </article>
     {% endfor %}
{% endblock content %}

templates/artilce/list1.html
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章列表页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
    <div id="article_row">
        <!--如果有searchd动作-->
        {% if search %}
            <!--如果检索到了内容-->
            {% if articles %}
                <h4 id="article_resutl1"><span>"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
                {% for article in articles %}
                <!-- 文章内容 -->
                <div id="article_list">
                <div id="article_img">
                    <a target="_blank" href="{% url 'article:article_detail' article.id %}">
                        <img src="{{ article.avatar.url }}" alt="">
                    </a>
                </div>
                <div id="article_info">
                  <dl>
                    <dt class="article_title">
                        <a href="{% url 'article:article_detail' article.id %}" target="_blank" >{{article.title}}</a>
                    </dt>
                    <div class="free">
                        <span class="name">
                            <a href="" title="" rel="author">{{article.author}}</a>
                        </span>
                        <span class="identity"></span>
                        <span class="time">{{article.created_time}}</span>
                    </div>
                      {% if article.body %}
                        <dd class="text">
                            <span>{{article.body|safe|slice:'122'}}</span>
                            <span class="test_body" style="display: none">{{article.body|safe}}</span>
                        </dd>
                      {% else %}
                          <dd class="text">
                            <span>{{article.body1|striptags|slice:"130"}}</span>
                            <span class="test_body" style="display: none">{{article.body1|striptags|safe}}</span>
                          </dd>
                      {% endif %}
                  </dl>
                  <div id="article_boot">
                      <span class="tags">
                          {% if article.column %}
                          <a href="">{{article.column}}</a>
                          {% else %}
                              <a href="">栏目</a>
                          {% endif %}
                          <a class="two" href="">标签预留</a>
                      </span>
                      <div class="look">
                          <span class="plun"><a href="">0评论</a></span>
                          <span> 共 <strong>{{article.total_views}}</strong> 人围观</span>
                      </div>
                  </div>
                </div>
                </div>
                {% endfor %}
                <!--分页-->
                <div class="edit_quotes">
                <a href="?page=1&search={{ search }}">首页</a>
                {% if articles.has_previous %}
                    <a href="?page={{ articles.previous_page_number}}&search={{ search }}">上一页</a>
                    <a href="?page={{ articles.previous_page_number}}&search={{ search }}">{{articles.previous_page_number}}</a>
                {% else %}
                    <a class="disabled" href="">上一页</a>
                {% endif %}
                <a id="edit_current" href="?page={{articles.number}}&search={{ search }}">{{articles.number}}</a>
                {% if articles.has_next %}
                        <a href="?page={{ articles.next_page_number}}&search={{ search }}">{{ articles.next_page_number}}</a>
                       <a href="?page={{ articles.next_page_number}}&search={{ search }}">下一页</a>
                {% else %}
                    <a class="disabled" href="">下一页</a>
                {% endif %}
                <a href="?page={{ articles.paginator.num_pages }}&search={{ search }}">尾页</a>
                </div>
                <!--扩展js代码 关键字高亮显示-->
                <script type="text/javascript">
                    $(document).ready(function () {
                        <!--标题-->
                        var regExp = new RegExp("(>[^<]*?)"+"{{search}}"+"([^>]*?<)","gmi");
                        $('.article_title').each(function () {
                            this.innerHTML=this.innerHTML.replace(regExp,"$1<font color='#f92672'>"+"{{ search}}"+"</font>$2");
                        });
                        <!--正文-->
                        var regExp1 = new RegExp("{{search}}","gmi");
                        $('.text').each(function () {
                            <!--文章的内容-->
                            body = $(this).find(".test_body").html();
                            if (body){
                                var article_body = body.match(/\S{0,15}{{search}}\S{0,15}/gmi);
                                     <!--搜索里面的关键字-->
                                if(article_body){
                                    <!--取匹配结果的前三项-->
                                    var article_body1 = article_body.slice(0,3).join('');
                                    <!--替换-->
                                    var jieguo = article_body1.replace(regExp1,"<font color='#f92672'>"+"{{ search}}"+"</font>");
                                    this.innerHTML = jieguo;
                                }
                            }

                        });
                    });
                </script>
                <!--如果没有检索到内容-->
            {% else %}
                <h4 id="article_resutl2">对不起暂无<span>"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
            <!--如果没有search动作-->
        {% else %}
            {% for article in articles %}
            <!-- 文章内容 -->
            <div id="article_list">
                <div id="article_img">
                    <a target="_blank" href="{% url 'article:article_detail' article.id %}">
                        <img src="{{ article.avatar.url }}" alt="">
                    </a>
                </div>
                <div id="article_info">
                  <dl>
                    <dt>
                        <a href="{% url 'article:article_detail' article.id %}" target="_blank" >{{article.title}}</a>
                    </dt>
                    <div class="free">
                        <span class="name">
                            <a href="" title="" rel="author">{{article.author}}</a>
                        </span>
                        <span class="identity"></span>
                        <span class="time">{{article.created_time}}</span>
                    </div>
                        <div>
                      {% if article.body %}
                          <dd class="text">{{ article.body|safe|slice:'122' }}</dd>
                      {% else %}
                          {% autoescape off %}
                          <dd class="text">{{article.body1|striptags|slice:"130"}}</dd>
                          {% endautoescape %}
                      {% endif %}
                        </div>
                  </dl>
                  <div id="article_boot">
                      <span class="tags">
                          {% if article.column %}
                          <a href="">{{article.column}}</a>
                          {% else %}
                              <a href="">栏目</a>
                          {% endif %}
                          <a class="two" href="">标签预留</a>
                      </span>
                      <div class="look">
                          <span class="plun"><a href="">0评论</a></span>
                          <span> 共 <strong>{{article.total_views}}</strong> 人围观</span>
                      </div>
                  </div>
                </div>
            </div>
            {% endfor %}
                <!--分页-->
            <div class="edit_quotes">
            <a href="?page=1">首页</a>
            {% if articles.has_previous %}
                <a href="?page={{ articles.previous_page_number}}">上一页</a>
                <a href="?page={{ articles.previous_page_number}}">{{articles.previous_page_number}}</a>
            {% else %}
                <a class="disabled" href="">上一页</a>
            {% endif %}
            <a id="edit_current" href="?page={{articles.number}}">{{articles.number}}</a>
            {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}">{{ articles.next_page_number}}</a>
                   <a href="?page={{ articles.next_page_number }}">下一页</a>
            {% else %}
                <a class="disabled" href="">下一页</a>
            {% endif %}
            <a href="?page={{ articles.paginator.num_pages }}">尾页</a>
            </div>
        {% endif %}
        </div>
{% endblock content %}

templates/artilce/update.html
{% extends "base1.html" %}
{% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block head %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <scrpit type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></scrpit>
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'prism/prism.css' %}">
{% endblock head %}
{% block content %}
<div id="article_update">
            <form method="post" action=".">
                {% csrf_token %}
                <div id="update_before">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" id="title" name="title" value="{{ article.title }}">
                </div>
                <div id="update_after">
                    <label for="body">文章正文</label>
                    <textarea class="ckeditor" name="body1" id="body1">
                        {{ article.body1}}
                    </textarea>
                </div>
                <div id="update_column">
                    <label for="column">标签:</label>
                    <select id="column" name="column">
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                    {% if column.id == article.column.id %}
                                    selected
                                    {% endif %}">
                            {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit">保存修改</button>
                <button>取消</button>
            </form>
</div>
{% endblock content %}
{% block js %}
    <script>
        $(".django-ckeditor-widget").removeAttr('style');
        CKEDITOR.replace("body1",
            {
                height:450,
                image_previewText : ' ',
                extraPlugins:'codesnippet',
                <!--图片上传路径-->
                filebrowserImageUploadUrl : '/ckeditor/upload/',
            }
        );
    </script>
{% endblock js %}