book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    # 书籍列表
    path('book-list/', views.book_list, name='book_list'),
    # 书籍详情
    path('book-detail/<int:id>/', views.book_detail, name='book_detail'),
    # 书籍下载
    path('book-download/<int:id>/', views.download, name='download'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 用户管理页面
    path('admin/', admin.site.urls),
    # 文章界面
    path('article/', include('article.urls', namespace='arctile')),
    # 用户管理界面
    path('profile/', include('userprofile.urls', namespace='userporfile')),
    # 密码重置
    path('password-reset/', include('password_reset.urls')),
    # 用户评论
    path('comment/', include("comment.urls", namespace='comment')),
    # 上传文件
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # 书籍
    path('book/', include('book.urls', namespace='book')),
    # 视频
    path('video/', include('video.urls', namespace='video')),
    # 图片
    path('photo/', include('photo.urls', namespace='photo')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.utils import timezone
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
# 书籍的数据模型
class BookPost(models.Model):
    # 标题
    title = models.CharField(max_length=100)
    # 作者
    author = models.CharField(max_length=100)
    # 创建时间 默认写入创建时的时间
    created_time = models.DateTimeField(default=timezone.now)
    # 更新时间
    updated_time = models.DateTimeField(auto_now=True)
    # 下载文件名
    downname = models.CharField(max_length=100, blank=True)
    # 文章简介
    body = models.TextField(blank=True)
    # 文章正文 富文本模式编写
    body1 = RichTextUploadingField(blank=True)
    # 文章图片
    avatar = ProcessedImageField(
        upload_to='book/%Y%m%d',
        processors=[ResizeToFill(128,170)],
        format='JPEG',
        options={'quality': 100},
        blank=True,
    )
    class Meta:
        # 数据排序方式 倒序方式排序
        ordering = ('-created_time',)

        # 将文章标题返回
        def __str__(self):
            return self.title

book/views.py
from django.shortcuts import render, redirect
from  .models import BookPost
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from qiniu import Auth
import requests

access_key = 'lWGrdnCe4PYfR1oXKAJHtAPikJ0bKGl-XqksUl0z'
secret_key = 'YzAEvTs_p8RVNcbPtgVMPnpFmm1QnbNc0HaxaXTx'
q = Auth(access_key, secret_key)

# Create your views here.
# 书籍列表
def book_list(request):
    book_list = BookPost.objects.all()
    # 每页显示20篇文章
    paginator = Paginator(book_list,20)
    # 获取页码数
    page = request.GET.get('page')
    # 将页码数返回给books
    books = paginator.get_page(page)
    context = {'books':books}
    return render(request, 'book/blist.html', context)

#书籍详情
def book_detail(request, id):
    book = BookPost.objects.get(id=id)
    context = {'book':book}
    return render(request, 'book/bdetail.html', context)

# 书籍下载
def download(request, id):
    book = BookPost.objects.filter(id=id)
    filename = book[0].downname
    # 或者直接输入url的方式下载
    base_url = 'http://prucutqgp.bkt.clouddn.com/' + filename
    # 可以设置token过期时间
    private_url = q.private_download_url(base_url, expires=3600)
    return redirect(private_url)

templates/book/bdetail.html
{% extends "base1.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    书籍详情
{% endblock title %}
{% block head %}
    <style>
        .content{
            padding: 0 20px;
            background-color: #fff;
            border: 1px solid #EAEAEA;
            border-radius: 4px;
        }
    </style>
{% endblock head %}
{% block content %}
<ol id="mianbao" class="breadcrumb" style="background-color: white">
    <li class="breadcrumb-item"><a href="{% url 'book:book_list' %}">书籍列表</a></li>
    <li class="breadcrumb-item"><a href="#"></a></li>
    <li class="breadcrumb-item active">{{book.title}}</li>
</ol>
<header class="article-header">
    <h1 class="article-title">
        <a href="">{{book.title}}</a>
    </h1>
    <div class="article-meta">
        <span class="item article-meta-time">
      <time class="time" data-toggle="tooltip" data-placement="bottom" title="{{book.created_time}}">
          <i class="glyphicon glyphicon-time"></i> {{book.created_time}}
      </time>
      </span>
        <span class="item article-meta-source" data-toggle="tooltip" data-placement="bottom" title="{{book.author}}"><i class="glyphicon glyphicon-globe"></i> {{book.author}}</span>
        <span class="item article-meta-category" data-toggle="tooltip" data-placement="bottom" title="{{article.column}}"><i class="glyphicon glyphicon-list"></i> <a href="program" title="">{{article.column}}</a></span>
        <span class="item article-meta-views" data-toggle="tooltip" data-placement="bottom" title="查看：{{ article.total_views}}"><i class="glyphicon glyphicon-eye-open"></i> 共0人围观</span>
        <span class="item article-meta-comment" data-toggle="tooltip" data-placement="bottom" title="评论：0"><i class="glyphicon glyphicon-comment"></i> 0评论</span> </div>
</header>
 <article class="article-content">
    <p>{{ book.body1|safe}}</p>
    <p class="article-copyright hidden-xs">未经允许不得转载：<a href="">噼里啪啦博客</a> » <a href="article.html">php如何判断一个日期的格式是否正确</a></p>
</article>
<div class="article-tags">标签：<a href="" rel="tag">空白</a></div>
<div class="article-tags"><a href="{% url 'book:download' book.id %}" rel="tag">下载此书</a></div>
<div class="title" id="comment">
    <h3>评论 <small>抢沙发</small></h3>
</div>
<div id="respond">
    <form action="" method="post" id="comment-form">
      <div class="comment">
        <div class="comment-title"><img class="avatar" src="images/icon/icon.png" alt="" /></div>
        <div class="comment-box">
          <textarea placeholder="您的评论可以一针见血" name="comment" id="comment-textarea" cols="100%" rows="3" tabindex="1" ></textarea>
          <div class="comment-ctrl"> <span class="emotion"><img src="images/face/5.png" width="20" height="20" alt="" />表情</span>
            <div class="comment-prompt"> <i class="fa fa-spin fa-circle-o-notch"></i> <span class="comment-prompt-text"></span> </div>
            <input type="hidden" value="1" class="articleid" />
            <button type="submit" name="comment-submit" id="comment-submit" tabindex="5" articleid="1">评论</button>
          </div>
        </div>
      </div>
    </form>
</div>
<div id="postcomments">
    <ol class="commentlist">
      <li class="comment-content"><span class="comment-f">#1</span>
        <div class="comment-avatar"><img class="avatar" src="images/icon/icon.png" alt="" /></div>
        <div class="comment-main">
          <p><span class="address">河南郑州</span><span class="time">(2016-01-06)</span><br />
            这是匿名评论的内容这是匿名评论的内容，这是匿名评论的内容这是匿名评论的内容这是匿名评论的内容这是匿名评论的内容这是匿名评论的内容这是匿名评论的内容。</p>
        </div>
      </li>
    </ol>
  </div>
{% endblock content %}

templates/book/blist.html
{% extends "base1.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    书籍列表页
{% endblock title %}
{% block content %}
    <div class="title">
        <h3>书籍列表</h3>
      </div>
        {% for book in books %}
        <div  class="book_list">
            <ul>
                <li>
                    <div class="book">
                        <a href="{% url 'book:book_detail' book.id %}" class="cover"  target="_blank">
                            <img src="{{book.avatar.url}}"  style="display: block;">
                        </a>
                        <a href="{% url 'book:book_detail' book.id %}" class="title1" target="_blank">{{book.title}}</a>
                    </div>
                    <div class="info">
                        <p class="u-author">
                            <span>{{book.author}}</span>
                        </p>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
{% endblock content %}