book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    # 书籍列表
    path('book-list/', views.book_list, name='book_list'),
    # 书籍详情
    path('book-detail/<int:id>/', views.book_detail, name='book_detail'),
    # 书籍下载
    path('book-download/<int:id>/', views.download, name='download'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 用户管理页面
    path('admin/', admin.site.urls),
    # 文章界面
    path('article/', include('article.urls', namespace='arctile')),
    # 用户管理界面
    path('profile/', include('userprofile.urls', namespace='userporfile')),
    # 密码重置
    path('password-reset/', include('password_reset.urls')),
    # 用户评论
    path('comment/', include("comment.urls", namespace='comment')),
    # 上传文件
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # 书籍
    path('book/', include('book.urls', namespace='book')),
    # 视频
    path('video/', include('video.urls', namespace='video')),
    # 图片
    path('photo/', include('photo.urls', namespace='photo')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from . import views
app_name = 'video'

urlpatterns = [
    # 视频列表
    path('video-list/', views.video_list, name='video_list'),
    # 视频详情
    path('video-detail/<int:id>/', views.video_detail, name='video_detail'),
]

video/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class VideoPost(models.Model):
    # 标题
    title = models.CharField(max_length=100)
    # 作者 一个用户对应着多个文章，级联删除
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # 创建时间 默认写入创建时的时间
    created_time = models.DateTimeField(default=timezone.now)
    # 图片地址
    image_url = models.CharField(max_length=100)
    # 视频地址
    video_url =  models.CharField(max_length=100, blank=True)

    class Meta:
        # 数据排序方式 倒序方式排序
        ordering = ('-created_time',)

        # 将文章标题返回
        def __str__(self):
            return self.title

video/views.py
from django.shortcuts import render
from .models import VideoPost
from django.core.paginator import Paginator
# Create your views here.
# 视频列表
def video_list(request):
    video_list = VideoPost.objects.all()
    # 每页显示20篇文章
    paginator = Paginator(video_list,6)
    # 获取页码数
    page = request.GET.get('page')
    # 将页码数返回给books
    videos = paginator.get_page(page)
    context = {'videos':videos}
    return render(request, 'video/vlist.html', context)

# 视频详情
def video_detail(request, id):
    video = VideoPost.objects.get(id=id)
    context = {'video':video}
    return render(request, 'video/vdetail.html', context)

templates/video/vdetail.html
{% extends "base1.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    视频详情
{% endblock title %}
{% block head %}
    <link rel="stylesheet" href="{% static 'dist/DPlayer.min.css' %}" type='text/css' media='all'/>
{% endblock %}
{% block content %}<!-- 文章详情 -->
    <div id="detail_row">
        <ol class="breadcrumb" id="mianbao">
        <li class="breadcrumb-item"><a href="{% url 'video:video_list' %}">视频列表</a></li>
        <li class="breadcrumb-item"><a href="#"></a></li>
        <li class="breadcrumb-item active">{{video.title}}</li>
        </ol>
        <!-- 标题及作者 -->
        <h3>{{ video.title }}</h3>
        <div class="xinxi">
            <span>上传者者：{{ video.author }}</span>
            <span>|</span>
            <span>{{video.created_time}}</span>
        </div>
        <!-- 文章正文 -->
        <div id="detail_zhengwen">​
            <div id="dplayer"></div>
        </div>
        <div id="detail_time">
            类型: <a href="">留白</a>
        </div>
    </div>
{% endblock content %}
{% block js %}
    <script src="{% static 'dist/DPlayer.min.js' %}"></script>
    <script>
    (function(){
            var player = new DPlayer({
                    container:document.getElementById("dplayer"),
                    autoplay : false,
                    theme :	'#b7daff',
                    preload :"no",
                    video : {
                            "url":"{{video.video_url}}"
                    },
            });
            window.dplayers||(window.dplayers=[]);
            window.dplayers.push(player);
    })()
    </script>
{% endblock js %}

templates/video/vlist.html
{% extends "base1.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    视频列表页
{% endblock title %}
{% block head %}
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block content %}
    <div class="video_list">
    {% for video in videos %}
        <div class="one_video">
                <div class="zoom-container">
                    <a href="{% url 'video:video_detail' video.id %}">
                        <span class="zoom-caption">
                            <i class="icon-play fa fa-play"></i>
                        </span>
                        <img src="{{video.image_url}}">
                    </a>
                </div>
                <h3 class="vid-name">{{video.title}}</h3>
                <div class="info1">
                    <h5>By <a href="#">{{video.author}}</a></h5>
                    <span><i class="fa fa-calendar"></i>{{video.created_time}}</span>
                    <span><i class="fa fa-heart"></i>0</span>
                </div>
        </div>
    {% endfor %}
    </div>
{% endblock content %}