article/urls.py
from django.urls import path
from . import views
# 引入path
app_name = 'article'

urlpatterns = [
    # 首页
    path('article/',views.article, name='article'),
    # 文章列表
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>', views.artilce_detail, name='article_detail'),
    # 创建文章
    path('article-create/<int:mark_fu>', views.article_create, name='article_create'),
    # 删除文章
    path('article-delete/<int:id>', views.article_delete, name='article_delete'),
    # 修改文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    # 富文本修改文章
    path('article-update1/<int:id>/', views.article_update1, name='article_update1'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    # 书籍列表
    path('book-list/', views.book_list, name='book_list'),
    # 书籍详情
    path('book-detail/<int:id>/', views.book_detail, name='book_detail'),
    # 书籍下载
    path('book-download/<int:id>/', views.download, name='download'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 用户管理页面
    path('admin/', admin.site.urls),
    # 文章界面
    path('article/', include('article.urls', namespace='arctile')),
    # 用户管理界面
    path('profile/', include('userprofile.urls', namespace='userporfile')),
    # 密码重置
    path('password-reset/', include('password_reset.urls')),
    # 用户评论
    path('comment/', include("comment.urls", namespace='comment')),
    # 上传文件
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # 书籍
    path('book/', include('book.urls', namespace='book')),
    # 视频
    path('video/', include('video.urls', namespace='video')),
    # 图片
    path('photo/', include('photo.urls', namespace='photo')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='user_register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户协议
    path('agree/', views.user_agree, name='agree'),
    # 修改用户资料
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    {#浏览器兼容#}
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    {#响应式布局#}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link REL="SHORTCUT ICON" HREF="{% static "images/favicon.ico" %}"/>
    {#<标题>#}
    <title>{% block title %}{% endblock %}</title>
    <!--引入css-->
    {% block head %}{% endblock head %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/pastie.css' %}">
    <script src="{% static 'popper/popper.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/article_list.css' %}">
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css" media="all">
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <!--引入layer-->
    <script src="{% static 'layer/layer.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>
<body>
<div id="wrapper">
    {#导航栏#}
    <!--header1导航栏-->
    {#预留内容位置#}
    <div id="base_two">
        {% include 'header.html' %}
        {% include 'header1.html' %}
        <div id="base_content">
            {% block content %}{% endblock content %}
        </div>
        <div id="base_sidebar">
            <div id="gongao">
                <div style="margin:0 auto;white-space: nowrap;overflow:hidden;" id="scroll_div" class="scroll_div">
                    <div id="scroll_begin">
                        欢迎大家来到我的博客，这里用来记录一些编程知识和生活趣事，以及分享一些资源。
                    </div>
                    <div id="scroll_end"></div>
                </div>
            </div>
            <div id="demo" class="carousel slide" data-ride="carousel">
                <div class="title">
                    <h2>爱好</h2>
                </div>
                <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                    <li data-target="#demo" data-slide-to="1"></li>
                    <li data-target="#demo" data-slide-to="2"></li>
                </ul>
                <!-- 轮播图片 -->
                <div class="carousel-inner">
                    <div class="carousel-item active">
                    <img src="{% static 'images/shou1.jpg' %}">
                          <div class="carousel-caption">
                            <h3>篮球</h3>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/shou2.jpg' %}">
                        <div class="carousel-caption">
                            <h3>音乐</h3>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/shou3.jpg' %}">
                        <div class="carousel-caption">
                            <h3>旅游</h3>
                        </div>
                    </div>
                </div>
                <!-- 左右切换按钮 -->
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>
            <div class="widget_tag">
                <div class="title">
                    <h2>分类</h2>
                </div>
                <div class="d_tags">
                    {% for column in columns %}
                    <a href="">{{ column.title}}</a>
                    {% endfor %}
                </div>
            </div>
        {% if article_lists %}
            <div id="base_hot">
                <h4>热门文章TOP10</h4>
                <ul>
                    {% for article in article_lists %}
                    <li>
                        <a target="_blank" href="{% url 'article:article_detail' article.id %}">
                            <span class="text">{{ article.title|slice:'15'}}</span>
                            <span class="text-muted1">阅读({{article.total_views}})</span>
                        </a>
                    </li>
                    {% endfor%}
                </ul>
            </div>
        {% endif %}
        </div>
    </div>
</div>
{% block js %}{% endblock js %}
<script type="text/javascript">
        function ScrollImgLeft() {
            var speed = 50;
            var scroll_begin = document.getElementById("scroll_begin");
            var scroll_end = document.getElementById("scroll_end");
            var scroll_div = document.getElementById("scroll_div");
            scroll_end.innerHTML = scroll_begin.innerHTML;

            function Marquee() {
                if (scroll_end.offsetWidth - scroll_div.scrollLeft <= 0)
                    scroll_div.scrollLeft -= scroll_begin.offsetWidth;
                else
                    scroll_div.scrollLeft++;
            }

            var MyMar = setInterval(Marquee, speed);
            scroll_div.onmouseover = function () {
                clearInterval(MyMar);
            }
            scroll_div.onmouseout = function () {
                MyMar = setInterval(Marquee, speed);
            }
        }
</script>
<script type="text/javascript">ScrollImgLeft();</script>
</body>
</html>

templates/header.html
{% load staticfiles %}
<nav class="navbar navbar-expand-sm navbar-light bg-light" id="daohang">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'arctile:article_list' %}">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" onclick="collect_site()">收藏本站</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="" onclick="user_delete()">删除用户</a>
                </li>
            </ul>
            <ul class="nav ml-auto">
                <!-- Django的 if 模板语句 -->
                {% if user.is_authenticated %}
                    <!-- 如果用户已经登录，则变为登录后的显示 -->
                    <!--如果已经有头像-->
{#                    {% if profile.avatar %}#}
{#                        <li class="nav-item">#}
{#                            <img style="width: 20px; height: 20px;padding-bottom: 3px; "src="{{profile.avatar.url}}" alt="">#}
{#                        </li>#}
{#                    {% else %}#}
{#                         <li class="nav-item">#}
{#                            <img style="width: 20px; height: 20px;padding-bottom: 3px;" src="{% static 'images/moren.jpg'%}" alt="">#}
{#                        </li>#}
{#                    {% endif %}#}
                    <li class="nav-item">
                        <a class="nav-link" href="">{{user.username}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">身份:{% if user.is_superuser %}管理员{% else %}平民{% endif %}</a>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                           href="#">写文章</a>
                            <div class="dropdown-menu" id="header_dropdown">
                                <a class="dropdown-item" href="{% url 'arctile:article_create' mark_fu=1 %}">Markdown编辑器</a>
					            <a class="dropdown-item" href="{% url 'arctile:article_create' mark_fu=2 %}">富文本编辑器</a>
                            </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:edit' user.id %}">设置</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{% url "userprofile:logout" %}'>退出</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="user_delete()">删号跑路</a>
                    </li>
                <!-- 如果用户未登录，则显示 “登录” -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link">身份:游客</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="user_login()">登录</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'userporfile:user_register' %}">注册</a>
                    </li>
                    <li>
                        <a class="nav-link" href="#">找回密码</a>
                    </li>
                <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
</nav>
{% if user.is_authenticated %}
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                skin:'layui-layer-lan',
                title: ["确认删除",'font-size:18px'],
                content: "确认删除用户资料吗？<br/>删除后您的评论和文章依然可见,但是您不能使用此账号登录!",
                 area:['350px', '250px'],
                yes: function(index, layero) {
                    location.href='{% url "userprofile:delete" user.id %}'
                },
            })
        }
    </script>
{% endif %}

<script>
    function collect_site() {
        layer.open({
            skin:'layui-layer-lan',
            title: ["提示信息","font-size:18px"],
            icon:6,
            content: "请按 Ctrl+D 键添加到收藏夹！",
            btn:['确定'],
            area:['250px', '250px'],
            }
        )
    }
    function user_login() {
        layer.open({
            btn:[],
            skin:'layer_bg',
            area:['200px', '430px'],
            title:false,
            anim:1,
            content:'<div class="container">\n' +
                '    <div class="row">\n' +
                '        <div class="col-12">\n' +
                '            <form id="form1" method="post" action="##" onsubmit="return false">\n' +
                '                {% csrf_token %}\n' +
                '                <!-- 账号 -->\n' +
                '                <div class="form-group">\n' +
                '                    <label for="username" style="color:white">账号</label>\n' +
                '                    <input type="text" class="form-control" id="username" name="username">\n' +
                '                </div>\n' +
                '                <!-- 密码 -->\n' +
                '                <div class="form-group">\n' +
                '                    <label for="password" style="color:white">密码</label>\n' +
                '                    <input type="password" class="form-control" id="password" name="password">\n' +
                '                </div>\n' +
                '                <!--记住密码-->\n' +
                '                <div class="form-line">\n' +
                '\t\t\t\t\t<p></p>\n' +
                '\t\t\t\t\t<div>\n' +
                '\t\t\t\t\t\t<p>\n' +
                '\t\t\t\t\t\t\t<a href="#">忘记密码</a>\n' +
                '\t\t\t\t\t\t\t<a href="#">快速注册</a>\n' +
                '\t\t\t\t\t\t</p>\n' +
                '\t\t\t\t\t\t<input type="checkbox" name="isSaved" class="isSaved" id="isSaved">\n' +
                '\t\t\t\t\t\t<label for="isSaved" style="color:white">记住密码</label>\n' +
                '\t\t\t\t\t</div>\n' +
                '\t\t\t\t</div>\n' +
                '<div><span id="error_tip">用户名或者密码错误！</span></div>'+
                '                <div><!-- 提交按钮 -->\n' +
                '                    <p></p>\n' +
                ' <input type="hidden" name="next" value="{{ request.path }}">\n'+
                '                    <button type="submit" class="btn btn-primary" onclick="user_login1()">登录</button>\n' +
                '                </div>\n' +
                '            </form>\n' +
                '        </div>\n' +
                '    </div>\n' +
                '</div>',
            }
        );
    }
</script>
{% block js %}
    <script type="text/javascript">
        // 添加js
            //用户登录验证
            function user_login1() {
                $('#error_tip').hide();
                $.ajax({
                    type: "POST",//方法类型
                    dataType: "json",//预期服务器返回的数据类型
                    url: "/profile/login/",//url
                    data: $('#form1').serialize(),
                    success:function (data) {
                       if(data['statue']==0){
                            $('#error_tip').show();
                        }else if(data['statue']==1){
                           //关闭倒计时
                           layer.msg("您已经登录成功将于", {
                               time: 3000,
                               shade: 0.8,
                               area: ['40%','50px'],
                               success: function (layero, index) {
                                   var msg = layero.text();
                                   var i = 3;
                                   var timer = null;
                                   var fn = function () {
                                       layero.find(".layui-layer-content").text(msg + '' + i + '' +'秒后到达登录前页面!');
                                       if (!i) {
                                           layer.close(index);
                                           clearInterval(timer);
                                       }
                                       i--;
                                   };
                                   timer = setInterval(fn, 1000);
                                   fn();
                                   },
                           }, function () {
                               window.location.href = data['next'];
                               });

                       }
                    },
                    errot:function () {
                        console.log('程序异常!')
                    }
                });
            }
            //可能的新功能
    </script>
{% endblock js %}

templates/header1.html
<div id="header1">
    <p class="h_r_3"></p>
    <div id="header_block">
        <div id="log">
            <p id="xuan"><a href="#">欢迎光临噼里啪啦的网站</a></p>
        </div>
        <div id="base_sou">
            <form method="get" action="/article/article-list/">
                {% csrf_token %}
                <input type="text" id="zzk_q" class="search_input" onkeydown="" tabindex="3" name="search" required>
                <input id="zzk_sou" onclick="" type="submit" class="search_btn" value="搜索">
            </form>
        </div>
        <div class="clear"></div>
    </div>
    <p class="h_r_3"></p>
</div>